FROM openjdk:17
WORKDIR usr/src
ADD ./target/dashboard-0.0.1-SNAPSHOT.jar /usr/src/dashboard-0.0.1-SNAPSHOT.jar
ADD ./target/students.csv /usr/src/students.csv
ADD ./target/keystore.p12 /usr/src/keystore.p12
ENTRYPOINT ["java","-jar","dashboard-0.0.1-SNAPSHOT.jar"]